CREATE TABLE danceData (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
  studentId INTEGER NOT NULL,
  name TEXT(128) NOT NULL,
  scores TEXT(255) NOT NULL,
  actions TEXT(255) NOT NULL,
  scoreAvg REAL NOT NULL
)
